### ISSUE TITLE
open-source license, paper

### ISSUE THREAD

**Issue by jpata** [jedlimlx/Muon-Tomography-AI#1]
Hello,

I found your repository very interesting & useful for my research (ML-based particle reconstruction at CERN).
May I ask if you support open-source reuse of the code in your repository - and with what LICENSE file (e.g. Apache, MIT, GPL etc)?
Moreover, is there a published paper that we can use to cite your work?

Thanks!

**Comment by jedlimlx** [comment]
Hi, thanks for your interest!

Sorry for the delayed response. 

As this project is being currently submitted to a competition, I wanted to check on what was their policy on open distribution of the paper and the licensing of the code. However, they are taking quite some time to reply so I'll just let you know first that the code licensing will most likely not be an issue and I will probably release it under the MIT license.

As for the paper, I'm not sure if I can openly distribute it so I guess I can email you the paper? For now, you can probably cite the repository, but in the ideal case I will upload it to arXiv eventually.

Also just curious, what type of ML-based particle reconstruction are you doing? When I went to CERN on a school trip last year and some of the researchers talked about using GNNs for reconstructing the particle trajectories from detector events. Is that what you are working on? Or is it more similar to this project on looking at predicting the composition of an object from the scattering of particles?

**Comment by jpata** [comment]
Many thanks for the reply & good luck with the competition! I will wait for the paper with interest. 🙂

We're working on [full event reconstruction](https://arxiv.org/abs/2309.06782) with GNN-s, but we are interested in branching out to volumetric reconstruction from scattering tomography.

As far as I know, this repo is the best open result out there for ML reconstruction of per-particle scattering tomography 👍

**Comment by jedlimlx** [comment]
Hi, we are now able to distribute the paper freely so I have attached it [here](https://github.com/jedlimlx/Muon-Tomography-AI/files/13308912/Muons_Paper.pdf). Feel free to ask any questions :D.

However, the competition is not yet over. We will upload the paper to arXiv when the competition is over.

We also currently working on some improvements to the model and the results look quite promising 🥳 .

**Comment by jedlimlx** [comment]
Hi, the paper has been uploaded on arXiv at https://arxiv.org/abs/2312.17265.
```
@misc{lim2023munet,
      title={$\mu$-Net: ConvNext-Based U-Nets for Cosmic Muon Tomography}, 
      author={Li Xin Jed Lim and Ziming Qiu},
      year={2023},
      eprint={2312.17265},
      archivePrefix={arXiv},
      primaryClass={cs.CV}
}
```

You may cite it at the above. If you have any questions, feel free to re-open the issue.
